public static void BreakBoards()//UND
{
    GorillaScoreBoard[] array = Object.FindObjectsOfType<GorillaScoreBoard>();
    for (int i = 0; i < array.Length; i++)
    {
        array[i].boardText.text = "BOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCKBOARDFUCK";
    }
}
